AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for MSSQL Workshop'
Parameters:
  YourIP:
    Type: String
    Default: 1.1.1.1/32
  Password:
    Type: String
    Default: HNxZUH3nwk2DdGGC
  DomainName:
    Type: String
    Default: domain.name
Resources:
  vpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/aws-samples/amazon-ec2-mssql-workshop/master/resources/templates/vpc-3azs.yaml
      Parameters:
        VPCName: 'MSSQL-WS-VPC'
        ClientIP: !Ref YourIP
  managedADStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: vpcStack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/aws-samples/amazon-ec2-mssql-workshop/master/resources/templates/managed-ad.yaml
      Parameters:
        Name: !Ref DomainName
        Password: !Ref Password
        ShortName: !Select [0, !Split [".", !Ref DomainName]]
        VpcID: !GetAtt vpcStack.Outputs.VPC
        SubnetA: !GetAtt vpcStack.Outputs.SubnetAPublic
        SubnetB: !GetAtt vpcStack.Outputs.SubnetBPublic
  fsxStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: managedADStack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/aws-samples/amazon-ec2-mssql-workshop/master/resources/templates/fsx.yaml
      Parameters:
        Name: 'MSSQL-FSx'
        VpcID: !GetAtt vpcStack.Outputs.VPC
        SubnetC: !GetAtt vpcStack.Outputs.SubnetCPublic
        SecurityGroup: !GetAtt vpcStack.Outputs.SecurityGroup
        DirectoryID: !GetAtt managedADStack.Outputs.myDirectory
  iamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/aws-samples/amazon-ec2-mssql-workshop/master/resources/templates/iam.yaml
      Parameters:
        Name: 'AllowEC2FC'
